package test.pruebagit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class objetoprueba implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nombre;
	private java.lang.Integer id_objeto;

	public objetoprueba() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.Integer getId_objeto() {
		return this.id_objeto;
	}

	public void setId_objeto(java.lang.Integer id_objeto) {
		this.id_objeto = id_objeto;
	}

	public objetoprueba(java.lang.String nombre, java.lang.Integer id_objeto) {
		this.nombre = nombre;
		this.id_objeto = id_objeto;
	}

}